package enumerations;

public enum NomsTuiles {
    Heliport,
    Caverne_Des_Ombres,
    Caverne_Du_Brasier,
    Foret_Pourpre,
    Porte_D_Argent,
    Porte_De_Bronze,
    Porte_De_Cuivre,
    Porte_De_Fer,
    Porte_D_Or,
    Tour_De_Guet,
    Jardin_Des_Hurlements,
    Jardin_Des_Murmures,
    Lagon_Perdu,
    Marais_Brumeux,
    Palais_De_Corail,
    Palais_Des_Marees,
    Pont_Des_Abimes,
    Rocher_Fantome,
    Dunes_De_L_Illusion,
    Falaises_De_L_Oubli,
    Temple_De_La_Lune,
    Temple_Du_Soleil,
    Val_Du_Crepuscule,
    Observatoire,
}
